package model

const (
	DB_NAME = "SERVER_MANAGEMENT.db"

	// STATUS_ROW table informations
	STATUS_ROW_TB_NAME = "STATUS_ROW"
	STATUS_ROW_ID = "ID"
	STATUS_ROW_DESCRIBE = "DESCRIBE"

	// DC table informations
	DC_TB_NAME = "DC"
	DC_ID = "ID"
	DC_DESCRIBE = "DESCRIBE"
	DC_STATUS_ROW = "ID_STATUS_ROW"

	// RACK table informations
	RACK_TB_NAME = "RACK"
	RACK_ID = "ID"
	RACK_DESCRIBE = "DESCRIBE"
	RACK_ID_STATUS_ROW = "ID_STATUS_ROW"

	// RACK_UNIT table informations
	RACK_UNIT_TB_NAME = "RACK_UNIT"
	RACK_UNIT_DESCRIBE = "DESCRIBE"
	RACK_UNIT_ID_STATUS_ROW = "ID_STATUS_ROW"

	// PORT_TYPE table informations
	PORT_TYPE_TB_NAME = "PORT_TYPE"
	PORT_TYPE_ID = "ID"
	PORT_TYPE_DESCRIBE = "DESCRIBE"
	PORT_TYPE_ID_STATUS_ROW = "ID_STATUS_ROW"

	// IP_NET table informations
	IP_NET_TB_NAME = "IP_NET"
	IP_NET_ID = "ID"
	IP_NET_VALUE = "VALUE"
	IP_NET_ID_STATUS_ROW = "ID_STATUS_ROW"

	// IP_HOST table informations
	IP_HOST_TB_NAME = "IP_HOST"
	IP_HOST_ID = "ID"
	IP_HOST_VALUE = "VALUE"
	IP_HOST_ID_STATUS_ROW = "ID_STATUS_ROW"

	// SERVER table informations
	SERVER_TB_NAME = "SERVER"
	SERVER_ID = "ID"
	SERVER_DC = "ID_DC"
	SERVER_RACK = "ID_RACK"
	SERVER_U_START = "ID_U_START"
	SERVER_U_END = "ID_U_END"
	SERVER_SERVICE = "ID_SERVICE"
	SERVER_ID_PORT_TYPE = "ID_PORT_TYPE"
	SERVER_SERIAL_NUMBER = "SERIAL_NUMBER"
	SERVER_STATUS_ROW = "ID_STATUS_ROW"

	// CABLE_TYPE table informations
	CABLE_TYPE_TB_NAME = "CABLE_TYPE"
	CABLE_TYPE_ID = "ID"
	CABLE_TYPE_NAME = "NAME"
	CABLE_TYPE_SIGN = "SIGN_PORT"
	CABLE_TYPE_ID_STATUS_ROW = "ID_STATUS_ROW"

	// SWITCH table informations
	SWITCH_TB_NAME = "SWITCH"
	SWITCH_ID = "ID"
	SWITCH_DESCRIBE = "DESCRIBE"
	SWITCH_ID_DC = "ID_DC"
	SWITCH_ID_RACK = "ID_RACK"
	SWITCH_ID_U_START = "ID_U_START"
	SWITCH_ID_U_END = "ID_U_END"
	SWITCH_ID_NET = "ID_IP_NET"
	SWITCH_IP_HOST = "ID_IP_HOST"
	SWITCH_MAX_PORT = "MAXIMUM_PORT"
	SWITCH_ID_STATUS_ROW = "ID_STATUS_ROW"

	// SWITCH_CONNECTION table informations
	SWITCH_CONNECTION_TB_NAME = "SWITCH_CONNECTION"
	SWITCH_CONNECTION_SERVER = "ID_SERVER"
	SWITCH_CONNECTION_SWITCH = "ID_SWITCH"
	SWITCH_CONNECTION_SV_PORT = "SV_PORT"
	SWITCH_CONNECTION_SWITCH_PORT = "SWITCH_PORT"
	SWITCH_CONNECTION_CABLE_TYPE = "ID_CABLE_TYPE"
	SWITCH_CONNECTION_ID_STATUS_ROW = "ID_STATUS_ROW"

	// IP_SERVER table informations
	IP_SERVER_TB_NAME = "IP_SERVER"
	IP_SERVER_ID_SERVER = "ID_SERVER"
	IP_SERVER_IP_NET = "ID_IP_NET"
	IP_SERVER_IP_HOST = "ID_IP_HOST"
	IP_SERVER_ID_STATUS_ROW = "ID_STATUS_ROW"

	// PERSON table informations
	PERSON_TB_NAME = "PERSON"
	PERSON_ID = "ID"
	PERSON_NAME = "NAME"
	PERSON_BIRTHDATE = "BIRTHDATE"
	PERSON_TEAM = "TEAM"
	PERSON_OTHER_INFO = "OTHER_INFO"
	PERSON_ID_STATUS_ROW = "ID_STATUS_ROW"

	// USER table informations
	USER_TB_NAME = "USER"
	USER_ID = "ID"
	USER_PASS = "PASS"
	USER_ID_PERSON = "ID_PERSON"
	USER_ID_STATUS_ROW = "ID_STATUS_ROW"

	// ERROR_STATUS table informations
	ERROR_STATUS_TB_NAME = "ERROR_STATUS"
	ERROR_STATUS_ID = "ID"
	ERROR_STATUS_DESCRIBE = "DESCRIBE"
	ERROR_STATUS_ID_STATUS_ROW = "ID_STATUS_ROW"

	// ERROR table informations
	ERROR_TB_NAME = "ERROR"
	ERROR_ID = "ID"
	ERROR_SUMMARY = "SUMMARY"
	ERROR_DESCRIBE = "DESCRIBE"
	ERROR_SOLUTION = "SOLUTION"
	ERROR_LAST_OCCURS = "LAST_OCCURS"
	ERROR_ID_SERVER = "ID_SERVER"
	ERROR_ID_ERROR_STATUS = "ID_ERROR_STATUS"
	ERROR_ID_STATUS_ROW = "ID_STATUS_ROW"

	// CURATTOR table informations
	CURATOR_TB_NAME = "CURATOR"
	CURATOR_ID_USER = "ID_USER"
	CURATOR_ID_ERROR = "ID_ERROR"
	CURATOR_ID_STATUS_ROW = "ID_STAUS_ROW"

	// LOG_ACTIVITY table informations
	LOG_ACTIVITY_TB_NAME = "LOG_ACTIVITY"
	LOG_ACTIVITY_ID = "ID"
	LOG_ACTIVITY_ID_USER = "ID_USER"
	LOG_ACTIVITY_OPERATION = "OPERATION"
	LOG_ACTIVITY_AFFECTED = "AFFECTED"
	LOG_ACTIVITY_AT = "AT"
	LOG_ACTIVITY_STATUS_ROW = "ID_STATUS_ROW"

	// PARAMETER table informations
	PARAMETER_TB_NAME = "PARAMETER"
)